#ifndef _STATEMENT_NODE_ATTR_H_
#define _STATEMENT_NODE_ATTR_H_

namespace TinyCompiler{

	//the kind of statement node
	enum class StatementNodeKind{
		STATEMENTNODE,

		LOOPSTATEMENTNODE,
		FORLOOPSTATEMENTNODE,
		WHILELOOPSTATEMENTNODE,

		CHECKSTATEMENTNODE,
		IFCHECKSTATEMENTNODE,

		SQUENCESTATEMENTNODE,
		ARITHMETICSQUENCESTATEMENTNODE,
		ASSIGNSQUENCESTATEMENTNODE,
		DEFINESQUENCESTATEMENTNODE,

		UNKNOWN,
	};
}

#endif